[project]
name = "mobilefacenet-pytorch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Cylix Lee", email = "cylix.lee@outlook.com" }]
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.3",
    "requests>=2.32.3",
 "torch>=2.6.0",
 "tqdm>=4.67.1",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

# On Linux, the CUDA 12.4 version of PyTorch will be installed; otherwise, the CPU version will be installed.
#
# Please see the document of uv at
# https://docs.astral.sh/uv/guides/integration/pytorch/#configuring-accelerators-with-environment-markers 
# to add your own configuration.
[tool.uv.sources]
torch = [
    { index = "pytorch-cpu", marker = "sys_platform != 'linux'" },
    { index = "pytorch-cu124", marker = "sys_platform == 'linux'" },
]
torchvision = [
    { index = "pytorch-cpu", marker = "sys_platform != 'linux'" },
    { index = "pytorch-cu124", marker = "sys_platform == 'linux'" },
]

# Index configuration

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[tool.ruff]
line-length = 120
